name: dbg
version: 0.1.0.0
github: "Futarimiti/dbg"
license: BSD-3-Clause
author: "Carman Fu"
maintainer: "example@example.com"
copyright: "Carman Fu 2024"
extra-source-files:
  - README.md
  - CHANGELOG.md
# Metadata used when publishing your package
synopsis: Rust dbg ripoff
category: Development, Debugging
# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: yeah
default-extensions:
  - TemplateHaskell
  - ScopedTypeVariables
  - QuasiQuotes
  - OverloadedStrings
  - ImportQualifiedPost
dependencies:
  - base >= 4.7 && < 5
  - haskell-src-meta
  - template-haskell
  # dbgML
  - monad-logger
  - text
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
library:
  source-dirs: src
